services:
  app:
    container_name: express_service
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    image: denoland/deno:alpine
    ports:
      - "${API_HOST:-0.0.0.0}:${API_PORT:-3000}:8000/tcp"
