name = "gmod-express"
main = "./index.js"
workers_dev = true

compatibility_date = "2022-11-05"
rules = [
  { type = "ESModule", globs = ["setup_app.js"] }
]

[env.staging]
name = "gmod-express-staging"
kv_namespaces = [{binding= "GmodExpress", id = "db86034742fd4ed68399de24a2a65a54"}]
