version: "3.8"

services:
  kv:
    container_name: express_db
    image: eqalpha/keydb
    entrypoint: ["keydb-server"]
    volumes:
      - "./express_db.rdb:/tmp/express_db.rdb"
      - "./express_db.sock:/tmp/express_db.sock"

  app:
    container_name: express_service
    build: ../
    image: jarredsumner/bun:edge
    entrypoint: ["bun", "run", "index.js"]
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "${API_HOST:-0.0.0.0}:${API_PORT:-3000}:3000/tcp"
    depends_on:
      - kv
    volumes:
      - "./express_db.sock:/tmp/express_db.sock"
